[workspace]
members = [
    "crates/fastqueue-common", 
    "crates/fastqueue-worker",
    "crates/fastqueue-cli"
]

[package]
name = "fastqueue_core"
version = "0.0.1"
edition = "2024"

[lib]
name = "fastqueue_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.2"
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "sync"] }
fastqueue-worker = { path = "./crates/fastqueue-worker" }
fastqueue-common = { path = "./crates/fastqueue-common"}
redis = "1.0.2"
uuid = { version = "1.19.0", features = ["v4"] }
