[package]
name = "fastqueue_core"
version = "0.0.1"
edition = "2024"

[lib]
name = "fastqueue_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.2"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "sync"] }
