[package]
name = "fastqueue-worker"
version = "0.1.0"
edition = "2024"

[lib]
name = "fastqueue_worker"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
